### ISSUE TITLE
Allow users to get order book in double numbers

### ISSUE THREAD

**Issue by Gobain** [walltime/walltime-cli#5]
Currently, the `walltime orderbook` command returns a JSON containing the orders in the order book within not evaluated operations.
The goal of this issue is to create an option for to users call `walltime orderbook` and shows the results in evaluated float format.

**Comment by felipelalli** [comment]
It can be easily done with this library:
http://john-edwin-tobey.org/Scheme/javascript-bignum/docs/files/schemeNumber-js.html
`
fn['inexact'](new SchemeNumber('string value here'));`

where 'string value here' is something like '1/3'.

**Comment by Gobain** [comment]
I already made the needed modification using pure Javascript. I'm just testing. Thank you for the tip.

**Comment by felipelalli** [comment]
Pure Javascript won't work with huge numbers. Actually, even `fn['inexact'](new SchemeNumber('string value here'));` won't work.

You should do it:

```
function makeZeroes(howMany) {
      let zeroes = '';

      for (var i = 0; i < howMany; i++) {
          zeroes += '0';
      }

      return zeroes;
  }
```

    function exactToInexact(schemeRawNumber, precision, roundUp, convertToFloat) {
        if (!fn['exact?'](schemeRawNumber)) {
            console.warn('A non exact number!', schemeRawNumber);
        }

        let modified = new SchemeNumber(schemeRawNumber);
        let bigNumber = '1' + makeZeroes(precision);

        modified = fn['*'](modified, new SchemeNumber(bigNumber));
        let roundFn = roundUp ? fn.ceiling : fn.floor;
        modified = roundFn(modified);
        modified = fn['/'](modified, new SchemeNumber(bigNumber));
        let convertedNumber = modified.toFixed(precision);

        return convertToFloat ? parseFloat(convertedNumber) : convertedNumber;
    }
